import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import { TheFooter } from '@/Components/TheFooter';
// import { TheHeader } from '@/Components/TheHeader';
import { StoreProvider } from '@/redux/StoreProvider';
import ThemeRegistry from './Componnets/ThemeRegistry';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
          {/* <TheHeader /> */}
          <ThemeRegistry options={{ key: 'mui' }}>{children}</ThemeRegistry>
          {/* <TheFooter /> */}
        </body>
      </html>
    </StoreProvider>
  );
}
