import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import { TheFooter } from '@/Components/TheFooter';
// import { TheHeader } from '@/Components/TheHeader';
import { StoreProvider } from '@/redux/StoreProvider';
import ThemeRegistry from './Componnets/ThemeRegistry';
import './globals.css';
import { Providers } from './Componnets/Layouts/Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode,
}) {
  // console.log(pageProps)
  return (
    <StoreProvider>
      <html lang="en">
        <body style={{ display: 'flex', flexDirection: 'column' }}>
          <Providers>
            {/* <TheHeader /> */}
            <ThemeRegistry options={{ key: 'mui' }}>{children}</ThemeRegistry>
            {/* <TheFooter /> */}
          </Providers>
        </body>
      </html>
    </StoreProvider>
  );
}
